import { auth,db } from "./firebase-config.js";import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";import { collection,addDoc,doc,getDoc,getDocs,updateDoc,deleteDoc,query,where,serverTimestamp,writeBatch } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";import { uploadImage } from "./cloudinary.js";import { privateProfile } from "./firebase-data.js";
UI.shell("author");const quill=new Quill("#chapterEditorQuill",{theme:"snow",placeholder:"Escreva o capítulo...",modules:{toolbar:[["bold","italic","underline"],[{header:[2,3,false]}],[{list:"ordered"},{list:"bullet"}],["blockquote"],["clean"]]}});let user=null,books=[],coverCurrent="";
UI.$$("[data-panel]").forEach(b=>b.onclick=()=>show(b.dataset.panel));function show(id){UI.$$("[data-panel]").forEach(x=>x.classList.toggle("active",x.dataset.panel===id));UI.$$(".panel-view").forEach(x=>x.classList.toggle("hidden",x.id!==id))}
onAuthStateChanged(auth,async u=>{if(!u||u.isAnonymous){location.replace("login.html");return}user=u;const p=await privateProfile(u.uid).catch(()=>null);UI.$("#bookAuthor").value=p?.nome||u.displayName||"";await loadBooks()});
async function loadBooks(){const s=await getDocs(query(collection(db,"livros"),where("criadoPor","==",user.uid)));books=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>UI.timeMs(b.criadoEm)-UI.timeMs(a.criadoEm));const chapters=await Promise.all(books.map(async b=>{const x=await getDocs(query(collection(db,"capitulos"),where("livroId","==",b.id)));return x.docs.length}));UI.$("#panelKpis").innerHTML=`<div class="kpi"><span>Meus livros</span><strong>${books.length}</strong></div><div class="kpi"><span>Publicados</span><strong>${books.filter(b=>b.status==="publicado").length}</strong></div><div class="kpi"><span>Rascunhos</span><strong>${books.filter(b=>b.status!=="publicado").length}</strong></div><div class="kpi"><span>Capítulos</span><strong>${chapters.reduce((a,n)=>a+n,0)}</strong></div>`;UI.$("#authorBookList").innerHTML=books.length?`<table class="table"><thead><tr><th>Livro</th><th>Status</th><th>Ações</th></tr></thead><tbody>${books.map(b=>`<tr><td><strong>${UI.esc(b.titulo)}</strong><div class="muted small">${UI.esc(b.genero||"")}</div></td><td><span class="status ${b.status==="publicado"?"live":"draft"}">${UI.esc(b.status||"rascunho")}</span></td><td><div style="display:flex;gap:7px;flex-wrap:wrap"><button class="btn edit-book" data-id="${b.id}" style="height:34px">Editar</button><button class="btn chapters-book" data-id="${b.id}" style="height:34px">Capítulos</button><a class="btn" href="livro.html?id=${b.id}" style="height:34px">Abrir</a></div></td></tr>`).join("")}</tbody></table>`:`<div class="empty-state">Você ainda não criou nenhum livro.</div>`;UI.$("#chapterBook").innerHTML=books.length?`<option value="">Selecione...</option>${books.map(b=>`<option value="${b.id}">${UI.esc(b.titulo)}</option>`).join("")}`:`<option value="">Crie um livro primeiro</option>`;UI.$$(".edit-book").forEach(b=>b.onclick=()=>editBook(b.dataset.id));UI.$$(".chapters-book").forEach(b=>b.onclick=()=>{UI.$("#chapterBook").value=b.dataset.id;show("chapterEditor");loadChapters()})}
UI.$("#newBook").onclick=()=>{resetBook();show("bookEditor")};
function resetBook(){UI.$("#bookForm").reset();UI.$("#bookId").value="";UI.$("#bookEditorTitle").textContent="Novo livro";UI.$("#deleteBook").classList.add("hidden");coverCurrent=""}
function editBook(id){const b=books.find(x=>x.id===id);if(!b)return;UI.$("#bookId").value=id;UI.$("#bookTitle").value=b.titulo||"";UI.$("#bookAuthor").value=b.autor||"";UI.$("#bookGenre").value=b.genero||"Romance";UI.$("#bookStatus").value=b.status||"rascunho";UI.$("#bookDescription").value=b.sinopse||"";UI.$("#bookTags").value=(b.tags||[]).join(", ");UI.$("#bookMature").checked=b.maduro===true;coverCurrent=b.capa||"";UI.$("#bookEditorTitle").textContent=`Editar: ${b.titulo}`;UI.$("#deleteBook").classList.remove("hidden");show("bookEditor")}
UI.$("#bookForm").onsubmit=async e=>{e.preventDefault();const id=UI.$("#bookId").value,file=UI.$("#bookCover").files[0];try{let cover=coverCurrent;if(file){UI.toast("Enviando capa...");cover=await uploadImage(file)}const tags=UI.$("#bookTags").value.split(",").map(x=>x.trim()).filter(Boolean).slice(0,8);const data={titulo:UI.$("#bookTitle").value.trim(),autor:UI.$("#bookAuthor").value.trim(),genero:UI.$("#bookGenre").value,status:UI.$("#bookStatus").value,sinopse:UI.$("#bookDescription").value.trim(),tags,maduro:UI.$("#bookMature").checked,capa:cover,criadoPor:user.uid,atualizadoEm:serverTimestamp()};if(id)await updateDoc(doc(db,"livros",id),data);else await addDoc(collection(db,"livros"),{...data,criadoEm:serverTimestamp()});UI.toast("Livro salvo");resetBook();await loadBooks();show("myBooks")}catch(err){console.error(err);UI.toast(err.message||"Não foi possível salvar")}};
UI.$("#deleteBook").onclick=async()=>{const id=UI.$("#bookId").value;if(!id||!confirm("Excluir este livro e todos os capítulos?"))return;const s=await getDocs(query(collection(db,"capitulos"),where("livroId","==",id)));let batch=writeBatch(db);s.docs.forEach(x=>batch.delete(x.ref));batch.delete(doc(db,"livros",id));await batch.commit();UI.toast("Livro excluído");resetBook();await loadBooks();show("myBooks")};
UI.$("#chapterBook").onchange=loadChapters;async function loadChapters(){const id=UI.$("#chapterBook").value;if(!id){UI.$("#chapterList").innerHTML=`<div class="empty-state">Selecione um livro.</div>`;return}const s=await getDocs(query(collection(db,"capitulos"),where("livroId","==",id)));const list=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>Number(a.numero)-Number(b.numero));UI.$("#chapterList").innerHTML=list.length?list.map(c=>`<div class="chapter"><span class="chapter-num">${c.numero}</span><span><strong>${UI.esc(c.titulo)}</strong><span>${UI.esc(c.status||"rascunho")}</span></span><button class="btn edit-chapter" data-id="${c.id}" style="height:34px">Editar</button></div>`).join(""):`<div class="empty-state">Nenhum capítulo ainda.</div>`;UI.$$(".edit-chapter").forEach(b=>b.onclick=()=>editChapter(b.dataset.id))}
async function editChapter(id){const s=await getDoc(doc(db,"capitulos",id));if(!s.exists())return;const c=s.data();UI.$("#chapterId").value=id;UI.$("#chapterNumber").value=c.numero||"";UI.$("#chapterTitle").value=c.titulo||"";UI.$("#chapterSummary").value=c.resumo||"";UI.$("#chapterStatus").value=c.status||"rascunho";quill.root.innerHTML=c.texto||"";UI.$("#cancelChapter").classList.remove("hidden");UI.$("#deleteChapter").classList.remove("hidden")}
function resetChapter(){UI.$("#chapterId").value="";UI.$("#chapterNumber").value="";UI.$("#chapterTitle").value="";UI.$("#chapterSummary").value="";UI.$("#chapterStatus").value="rascunho";quill.setText("");UI.$("#cancelChapter").classList.add("hidden");UI.$("#deleteChapter").classList.add("hidden")}
UI.$("#cancelChapter").onclick=resetChapter;UI.$("#chapterForm").onsubmit=async e=>{e.preventDefault();const bookId=UI.$("#chapterBook").value,b=books.find(x=>x.id===bookId);if(!b)return UI.toast("Selecione um livro.");const id=UI.$("#chapterId").value,text=quill.root.innerHTML.trim();if(quill.getText().trim().length<2)return UI.toast("Escreva o capítulo.");const data={livroId:bookId,livroTitulo:b.titulo,numero:Number(UI.$("#chapterNumber").value),titulo:UI.$("#chapterTitle").value.trim(),resumo:UI.$("#chapterSummary").value.trim(),texto:text,status:UI.$("#chapterStatus").value,criadoPor:user.uid,atualizadoEm:serverTimestamp()};if(id)await updateDoc(doc(db,"capitulos",id),data);else await addDoc(collection(db,"capitulos"),{...data,criadoEm:serverTimestamp()});UI.toast("Capítulo salvo");resetChapter();await loadChapters();await loadBooks()};
UI.$("#deleteChapter").onclick=async()=>{const id=UI.$("#chapterId").value;if(!id||!confirm("Excluir este capítulo?"))return;await deleteDoc(doc(db,"capitulos",id));UI.toast("Capítulo excluído");resetChapter();await loadChapters();await loadBooks()};
