import { auth } from "./firebase-config.js";import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { chapterContext,saveProgress,registerView,likeState,toggleLike,comments,addComment,deleteComment,privateProfile } from "./firebase-data.js";
const id=new URLSearchParams(location.search).get("id"),content=UI.$("#readerContent");let ctx=null,user=null,profile=null;
const savedTheme=localStorage.getItem("ec-reader-theme")||"dark";document.documentElement.dataset.readerTheme=savedTheme;UI.$("#readerTheme").value=savedTheme;
UI.$("#readerPrefs").onclick=()=>UI.$("#readerSettings").classList.toggle("hidden");UI.$("#readerTheme").onchange=e=>{localStorage.setItem("ec-reader-theme",e.target.value);document.documentElement.dataset.readerTheme=e.target.value};
UI.$("#fontDown").onclick=()=>font(-1);UI.$("#fontUp").onclick=()=>font(1);function font(d){const px=parseFloat(getComputedStyle(content).fontSize);content.style.fontSize=`${Math.max(15,Math.min(28,px+d))}px`}
onAuthStateChanged(auth,async u=>{user=u&&!u.isAnonymous?u:null;if(user)profile=await privateProfile(user.uid).catch(()=>null);if(ctx){await renderLike();renderCommentForm()}});
try{ctx=await chapterContext(id);if(!ctx)throw new Error("Capítulo indisponível");const {book,chapter,chapters,index,previous,next}=ctx;document.title=`${chapter.title} · ${book.title}`;UI.$("#readerBook").textContent=book.title;UI.$("#readerChapter").textContent=`Capítulo ${chapter.number} · ${chapter.title}`;UI.$("#backBook").href=`livro.html?id=${book.id}`;UI.$("#readerHeading").innerHTML=`<div class="chapter-kicker">CAPÍTULO ${chapter.number}</div><h1>${UI.esc(chapter.title)}</h1><div class="muted small">${UI.esc(book.title)}</div>`;renderText(chapter.text);UI.$("#prev").href=previous?`leitura.html?id=${previous.id}`:`livro.html?id=${book.id}`;UI.$("#prev").textContent=previous?"← Anterior":"← Livro";UI.$("#next").href=next?`leitura.html?id=${next.id}`:`livro.html?id=${book.id}`;UI.$("#next").textContent=next?"Próximo →":"Finalizar";const pct=chapters.length?Math.round((index+1)/chapters.length*100):100;UI.$("#readPct").textContent=`${pct}%`;UI.$("#readBar").style.width=`${pct}%`;localStorage.setItem("ultimoCapituloLido",JSON.stringify({capituloId:chapter.id,livroId:book.id,livroTitulo:book.title,capa:book.cover,numero:chapter.number,atualizadoEm:Date.now()}));if(auth.currentUser&&!auth.currentUser.isAnonymous)await saveProgress(auth.currentUser,ctx).catch(()=>{});const views=await registerView(ctx).catch(()=>0);UI.$("#viewCount").textContent=`◉ ${UI.fmt(views)}`;await renderLike();await renderComments();renderCommentForm()}catch(e){console.error(e);UI.$("#readerHeading").innerHTML=`<div class="chapter-kicker">ENTRE CAPÍTULOS</div><h1>Capítulo indisponível</h1>`;content.innerHTML=`<p>Não foi possível carregar este capítulo.</p>`}
function renderText(raw=""){content.innerHTML="";const text=String(raw||"").replace(/\u00a0/g," ").trim();if(!text){content.innerHTML="<p>Este capítulo ainda não possui texto.</p>";return}if(/<\/?[a-z][\s\S]*>/i.test(text)){const p=new DOMParser().parseFromString(text,"text/html");p.querySelectorAll("script,style,iframe,object,embed,link,meta").forEach(x=>x.remove());p.querySelectorAll("*").forEach(el=>{[...el.attributes].forEach(a=>{if(a.name.toLowerCase().startsWith("on")||(["src","href"].includes(a.name.toLowerCase())&&String(a.value).toLowerCase().startsWith("javascript:")))el.removeAttribute(a.name)});["width","min-width","max-width","white-space","position","left","right","transform","margin-left","margin-right","font-size","line-height","font-family"].forEach(x=>el.style?.removeProperty(x));el.removeAttribute("width")});content.append(...p.body.childNodes)}else text.split(/\n\s*\n/).forEach(t=>{const p=document.createElement("p");p.textContent=t.replace(/\n/g," ").replace(/\s+/g," ").trim();content.appendChild(p)})}
async function renderLike(){if(!ctx)return;const s=await likeState(user,ctx.chapter.id).catch(()=>({liked:false,count:0}));const b=UI.$("#likeBtn");b.textContent=`${s.liked?"♥":"♡"} Curtir · ${s.count}`;b.onclick=async()=>{if(!user){location.href="login.html";return}const x=await toggleLike(user,ctx.chapter.id);b.textContent=`${x.liked?"♥":"♡"} Curtir · ${x.count}`}}
function renderCommentForm(){if(!ctx)return;UI.$("#commentForm").innerHTML=user?`<div class="comment-box"><textarea id="commentText" maxlength="1200" placeholder="Escreva um comentário..."></textarea><button id="sendComment" class="btn btn-primary">Publicar</button></div>`:`<div class="notice"><a class="link" href="login.html">Entre</a> para comentar.</div>`;const b=UI.$("#sendComment");if(b)b.onclick=async()=>{const text=UI.$("#commentText").value.trim();if(text.length<2)return UI.toast("Escreva pelo menos 2 caracteres.");await addComment(user,ctx,text,profile);UI.$("#commentText").value="";await renderComments();UI.toast("Comentário publicado")}}
async function renderComments(){const list=await comments(ctx.chapter.id).catch(()=>[]);UI.$("#comments").innerHTML=list.length?list.map(c=>`<div class="review"><div class="review-head"><div class="review-user"><span class="review-avatar" ${c.fotoUsuario?`style="background-image:url('${UI.esc(c.fotoUsuario)}')"`:""}>${c.fotoUsuario?"":UI.initials(c.nomeUsuario||"Leitor")}</span><div><strong>${UI.esc(c.nomeUsuario||"Leitor")}</strong><div class="muted small">${UI.timeAgo(c.criadoEm)}</div></div></div>${user&&c.usuarioId===user.uid?`<button class="btn btn-danger delete-comment" data-id="${c.id}" style="height:32px">Excluir</button>`:""}</div><p>${UI.esc(c.comentario||"")}</p></div>`).join(""):`<div class="empty-state">Nenhum comentário ainda.</div>`;UI.$$(".delete-comment").forEach(b=>b.onclick=async()=>{await deleteComment(b.dataset.id);await renderComments()})}
