import { auth,db } from "./firebase-config.js";import { onAuthStateChanged,updateProfile } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";import { doc,getDoc,setDoc,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";import { uploadImage } from "./cloudinary.js";
UI.shell("settings");UI.$$("[data-tab]").forEach(b=>b.onclick=()=>{UI.$$("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");UI.$$(".tab-panel").forEach(x=>x.classList.add("hidden"));UI.$(`#${b.dataset.tab}`).classList.remove("hidden")});
const pref=localStorage.getItem("ec-theme")||"dark";UI.$$("[data-theme]").forEach(b=>{b.classList.toggle("active",b.dataset.theme===pref);b.onclick=()=>{UI.setTheme(b.dataset.theme);UI.$$("[data-theme]").forEach(x=>x.classList.toggle("active",x===b))}});
const rt=localStorage.getItem("ec-reader-theme")||"dark";UI.$("#readerThemeSetting").value=rt;UI.$("#readerThemeSetting").onchange=e=>localStorage.setItem("ec-reader-theme",e.target.value);
const rm=localStorage.getItem("ec-reduce-motion")==="1";UI.$("#reduceMotion").checked=rm;UI.$("#reduceMotion").onchange=e=>{localStorage.setItem("ec-reduce-motion",e.target.checked?"1":"0");document.documentElement.style.scrollBehavior=e.target.checked?"auto":""};
onAuthStateChanged(auth,async u=>{if(!u||u.isAnonymous){UI.$("#profile").innerHTML=`<div class="empty-state"><a class="link" href="login.html">Entre</a> para editar seu perfil.</div>`;UI.$("#support").innerHTML=`<div class="empty-state"><a class="link" href="login.html">Entre</a> para configurar apoio.</div>`;return}const [us,as]=await Promise.all([getDoc(doc(db,"usuarios",u.uid)),getDoc(doc(db,"autores",u.uid))]);const p=us.exists()?us.data():{},a=as.exists()?as.data():{};UI.$("#settingsName").value=p.nome||u.displayName||"";UI.$("#settingsBio").value=p.biografia||"";const social=a.redesSociais||p.redesSociais||{};UI.$("#socialInstagram").value=social.instagram||"";UI.$("#socialTikTok").value=social.tiktok||"";UI.$("#socialYouTube").value=social.youtube||"";UI.$("#socialTwitter").value=social.twitter||"";UI.$("#socialFacebook").value=social.facebook||"";UI.$("#socialSite").value=social.site||"";UI.$("#pixKey").value=a.pixChave||"";UI.$("#pixName").value=a.pixNome||"";UI.$("#supportUrl").value=a.apoioUrl||"";UI.$("#supportMessage").value=a.apoioMensagem||"";
 UI.$("#profileForm").onsubmit=async e=>{e.preventDefault();const name=UI.$("#settingsName").value.trim(),bio=UI.$("#settingsBio").value.trim();const socialLinks={instagram:UI.$("#socialInstagram").value.trim(),tiktok:UI.$("#socialTikTok").value.trim(),youtube:UI.$("#socialYouTube").value.trim(),twitter:UI.$("#socialTwitter").value.trim(),facebook:UI.$("#socialFacebook").value.trim(),site:UI.$("#socialSite").value.trim()};if(Object.values(socialLinks).some(url=>url&&!UI.safeHttps(url)))return UI.toast("Use links HTTPS válidos nas redes sociais.");let photo=p.fotoURL||u.photoURL||"",file=UI.$("#settingsPhoto").files[0];try{if(file){UI.toast("Enviando foto...");photo=await uploadImage(file,{kind:"avatar"})}await setDoc(doc(db,"usuarios",u.uid),{uid:u.uid,nome:name,biografia:bio,fotoURL:photo,email:u.email||"",redesSociais:socialLinks,atualizadoEm:serverTimestamp()},{merge:true});await setDoc(doc(db,"autores",u.uid),{uid:u.uid,nome:name,biografia:bio,fotoURL:photo,redesSociais:socialLinks,atualizadoEm:serverTimestamp()},{merge:true});await updateProfile(u,{displayName:name,photoURL:photo||null});UI.toast("Perfil atualizado")}catch(err){console.error(err);UI.toast(err.message||"Não foi possível salvar")}};
 UI.$("#supportForm").onsubmit=async e=>{e.preventDefault();const url=UI.$("#supportUrl").value.trim();if(url&&!UI.safeHttps(url))return UI.toast("Use um link HTTPS válido.");await setDoc(doc(db,"autores",u.uid),{uid:u.uid,nome:UI.$("#settingsName").value.trim()||p.nome||u.displayName||"Autor",biografia:UI.$("#settingsBio").value.trim()||p.biografia||"",fotoURL:p.fotoURL||u.photoURL||"",pixChave:UI.$("#pixKey").value.trim(),pixNome:UI.$("#pixName").value.trim(),apoioUrl:url,apoioMensagem:UI.$("#supportMessage").value.trim(),atualizadoEm:serverTimestamp()},{merge:true});UI.toast("Formas de apoio salvas")};
});
